### ISSUE TITLE
Investigate panic

### ISSUE THREAD

**Issue by leelynne** [leelynne/sqserv#5]
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10475 goroutine 27413624 [running]:
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10475 panic(0xa01c20, 0xc820012070)
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10476   /var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.6/src/runtime/panic.go:464 +0x3e6
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10476 github.com/Remitly/dataserv/vendor/github.com/leelynne/sqserv.(_SQSServer).serveMessage(0xc8204c1570, 0x7f91d9b31818, 0xc820a00900, 0xc820305920, 0xc820ee4b40, 0x3c)
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10477   /var/lib/jenkins/workspace/dataserv/src/github.com/Remitly/dataserv/vendor/github.com/leelynne/sqserv/server.go:273 +0x821
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10478 created by github.com/Remitly/dataserv/vendor/github.com/leelynne/sqserv.(_SQSServer).run
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10485   /var/lib/jenkins/workspace/dataserv/src/github.com/Remitly/dataserv/vendor/github.com/leelynne/sqserv/server.go:244 +0x8f4
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.10821 Starting dataserv from /var/deploy/apps/dataserv/latest
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.11475 t=2016-08-25T02:22:53+0000 lvl=info msg="Starting debug endpoint" port=7450
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.11477 t=2016-08-25T02:22:53+0000 lvl=info msg="Starting http service" port=9412
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.11479 t=2016-08-25T02:22:53+0000 lvl=info msg="Starting http ad trackr service" port=8000
Aug 24 19:23:02 dataserv-prod-i-f895256d dataserv:  2016-08-25_02:22:53.11503 t=2016-08-25T02:22:53+0000 lvl=info msg="Starting polling for queues [uel-us-west-2 datapipeline_ingress uel-us-west-1 uel-us-west-1]"

**Comment by leelynne** [comment]
No Repro.
